<<<<<<< HEAD
export { default as AdminIcon } from './AdminIcon'
export { default as ArchiveIcon } from './ArchiveIcon'
export { default as ArrowDownIcon } from './ArrowDownIcon'
export { default as BondIcon } from './BondIcon'
export { default as BubblesIcon } from './BubblesIcon'
export { default as ChartIcon } from './ChartIcon'
export { default as CheckIcon } from './CheckIcon'
export { default as ClockIcon } from './ClockIcon'
export { default as ConnectionsIcon } from './ConnectionsIcon'
export { default as CrossIconIcon } from './CrossIconIcon'
export { default as DashboardIcon } from './DashboardIcon'
export { default as DotsIcon } from './DotsIcon'
export { default as ManageIcon } from './ManageIcon'
export { default as MonitorIcon } from './MonitorIcon'
export { default as MoonIcon } from './MoonIcon'
export { default as PencilIcon } from './PencilIcon'
export { default as PlusIcon } from './PlusIcon'
export { default as SearchIcon } from './SearchIcon'
export { default as SortIcon } from './SortIcon'
export { default as SunIcon } from './SunIcon'
=======
export { ReactComponent as AdminIcon } from './admin.svg'
export { ReactComponent as ConnectionsIcon } from './connections.svg'
export { ReactComponent as DashboardIcon } from './dashboard.svg'
export { ReactComponent as ManageIcon } from './manage.svg'
export { ReactComponent as MonitorIcon } from './monitor.svg'

export { ReactComponent as SunIcon } from './sun.svg'
export { ReactComponent as MoonIcon } from './moon.svg'

export { ReactComponent as ArrowDownIcon } from './arrow-down.svg'
export { ReactComponent as CheckIcon } from './check-icon.svg'
export { ReactComponent as SearchIcon } from './search.svg'

export { ReactComponent as BubblesIcon } from './bubbles.svg'
export { ReactComponent as ArchiveIcon } from './archive.svg'
export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as BondIcon } from './bond.svg'

export { ReactComponent as ChartIcon } from './chart.svg'
export { ReactComponent as ClockIcon } from './clock.svg'
export { ReactComponent as SortIcon } from './sort.svg'

export { ReactComponent as ThreeDotIcon } from './three-dot.svg'
export { ReactComponent as CrossIcon } from './cross.svg'
export { ReactComponent as PencilIcon } from './pencil.svg'
>>>>>>> origin/main
